
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class CalculatorDisplay extends javax.swing.JFrame {
    private Double result, memoryResult, recentValue;
    private boolean clean, equalButtonIsClicked, expressionIsClicked;
    private char currentOperation;
    
    /**
     * Creates new form CalculatorDisplay
     */
    public CalculatorDisplay() {
        initComponents();
        initLocalVariable();
    }
    
    private void initLocalVariable() {
        result = 0.0;
        memoryResult = 0.0;
        recentValue = 0.0;
        clean = true;
        equalButtonIsClicked = false;
        expressionIsClicked = false;
        currentOperation = '#';
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDisplay = new javax.swing.JTextField();
        btnMC = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        btnMPlus = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btbMSub = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnContrast = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btn1Divide = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnCleanEntry = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("0");

        btnMC.setBackground(new java.awt.Color(255, 51, 0));
        btnMC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnMC.setText("MC");
        btnMC.setInheritsPopupMenu(true);
        btnMC.setMaximumSize(new java.awt.Dimension(25, 25));
        btnMC.setMinimumSize(new java.awt.Dimension(25, 25));
        btnMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMCMouseClicked(evt);
            }
        });

        btnMR.setBackground(new java.awt.Color(255, 51, 0));
        btnMR.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnMR.setText("MR");
        btnMR.setInheritsPopupMenu(true);
        btnMR.setMaximumSize(new java.awt.Dimension(25, 25));
        btnMR.setMinimumSize(new java.awt.Dimension(25, 25));
        btnMR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMRMouseClicked(evt);
            }
        });

        btnMPlus.setBackground(new java.awt.Color(255, 51, 0));
        btnMPlus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnMPlus.setText("M+");
        btnMPlus.setInheritsPopupMenu(true);
        btnMPlus.setMaximumSize(new java.awt.Dimension(25, 25));
        btnMPlus.setMinimumSize(new java.awt.Dimension(25, 25));
        btnMPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMPlusMouseClicked(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(0, 204, 255));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.setInheritsPopupMenu(true);
        btn7.setMaximumSize(new java.awt.Dimension(25, 25));
        btn7.setMinimumSize(new java.awt.Dimension(25, 25));
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(0, 204, 255));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.setInheritsPopupMenu(true);
        btn8.setMaximumSize(new java.awt.Dimension(25, 25));
        btn8.setMinimumSize(new java.awt.Dimension(25, 25));
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(0, 204, 255));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.setInheritsPopupMenu(true);
        btn9.setMaximumSize(new java.awt.Dimension(25, 25));
        btn9.setMinimumSize(new java.awt.Dimension(25, 25));
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(0, 204, 255));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.setInheritsPopupMenu(true);
        btn4.setMaximumSize(new java.awt.Dimension(25, 25));
        btn4.setMinimumSize(new java.awt.Dimension(25, 25));
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(0, 204, 255));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.setInheritsPopupMenu(true);
        btn5.setMaximumSize(new java.awt.Dimension(25, 25));
        btn5.setMinimumSize(new java.awt.Dimension(25, 25));
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(0, 204, 255));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.setInheritsPopupMenu(true);
        btn6.setMaximumSize(new java.awt.Dimension(25, 25));
        btn6.setMinimumSize(new java.awt.Dimension(25, 25));
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(0, 204, 255));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.setInheritsPopupMenu(true);
        btn3.setMaximumSize(new java.awt.Dimension(25, 25));
        btn3.setMinimumSize(new java.awt.Dimension(25, 25));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(0, 204, 255));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.setInheritsPopupMenu(true);
        btn2.setMaximumSize(new java.awt.Dimension(25, 25));
        btn2.setMinimumSize(new java.awt.Dimension(25, 25));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });

        btnDivide.setBackground(new java.awt.Color(0, 153, 51));
        btnDivide.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnDivide.setText("÷");
        btnDivide.setInheritsPopupMenu(true);
        btnDivide.setMaximumSize(new java.awt.Dimension(25, 25));
        btnDivide.setMinimumSize(new java.awt.Dimension(25, 25));
        btnDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivideMouseClicked(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(0, 204, 255));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.setInheritsPopupMenu(true);
        btn1.setMaximumSize(new java.awt.Dimension(25, 25));
        btn1.setMinimumSize(new java.awt.Dimension(25, 25));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });

        btbMSub.setBackground(new java.awt.Color(255, 51, 0));
        btbMSub.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btbMSub.setText("M-");
        btbMSub.setInheritsPopupMenu(true);
        btbMSub.setMaximumSize(new java.awt.Dimension(25, 25));
        btbMSub.setMinimumSize(new java.awt.Dimension(25, 25));
        btbMSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbMSubMouseClicked(evt);
            }
        });

        btnMultiply.setBackground(new java.awt.Color(0, 153, 0));
        btnMultiply.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnMultiply.setText("X");
        btnMultiply.setInheritsPopupMenu(true);
        btnMultiply.setMaximumSize(new java.awt.Dimension(25, 25));
        btnMultiply.setMinimumSize(new java.awt.Dimension(25, 25));
        btnMultiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplyMouseClicked(evt);
            }
        });

        btnSubtract.setBackground(new java.awt.Color(0, 153, 0));
        btnSubtract.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnSubtract.setText("-");
        btnSubtract.setInheritsPopupMenu(true);
        btnSubtract.setMaximumSize(new java.awt.Dimension(25, 25));
        btnSubtract.setMinimumSize(new java.awt.Dimension(25, 25));
        btnSubtract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubtractMouseClicked(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(51, 204, 255));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.setInheritsPopupMenu(true);
        btn0.setMaximumSize(new java.awt.Dimension(25, 25));
        btn0.setMinimumSize(new java.awt.Dimension(25, 25));
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });

        btnDot.setBackground(new java.awt.Color(0, 204, 255));
        btnDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnDot.setText(".");
        btnDot.setInheritsPopupMenu(true);
        btnDot.setMaximumSize(new java.awt.Dimension(25, 25));
        btnDot.setMinimumSize(new java.awt.Dimension(25, 25));
        btnDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDotMouseClicked(evt);
            }
        });

        btnContrast.setBackground(new java.awt.Color(0, 153, 0));
        btnContrast.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnContrast.setText("+/-");
        btnContrast.setInheritsPopupMenu(true);
        btnContrast.setMaximumSize(new java.awt.Dimension(25, 25));
        btnContrast.setMinimumSize(new java.awt.Dimension(25, 25));
        btnContrast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContrastMouseClicked(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 153, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setInheritsPopupMenu(true);
        btnAdd.setMaximumSize(new java.awt.Dimension(25, 25));
        btnAdd.setMinimumSize(new java.awt.Dimension(25, 25));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnSquare.setBackground(new java.awt.Color(0, 153, 0));
        btnSquare.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnSquare.setText("√");
        btnSquare.setInheritsPopupMenu(true);
        btnSquare.setMaximumSize(new java.awt.Dimension(25, 25));
        btnSquare.setMinimumSize(new java.awt.Dimension(25, 25));
        btnSquare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSquareMouseClicked(evt);
            }
        });

        btnPercent.setBackground(new java.awt.Color(0, 153, 0));
        btnPercent.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnPercent.setText("%");
        btnPercent.setInheritsPopupMenu(true);
        btnPercent.setMaximumSize(new java.awt.Dimension(25, 25));
        btnPercent.setMinimumSize(new java.awt.Dimension(25, 25));
        btnPercent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPercentMouseClicked(evt);
            }
        });

        btn1Divide.setBackground(new java.awt.Color(0, 153, 0));
        btn1Divide.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1Divide.setText("1/X");
        btn1Divide.setInheritsPopupMenu(true);
        btn1Divide.setMaximumSize(new java.awt.Dimension(25, 25));
        btn1Divide.setMinimumSize(new java.awt.Dimension(25, 25));
        btn1Divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1DivideMouseClicked(evt);
            }
        });

        btnResult.setBackground(new java.awt.Color(0, 153, 0));
        btnResult.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnResult.setText("=");
        btnResult.setInheritsPopupMenu(true);
        btnResult.setMaximumSize(new java.awt.Dimension(25, 25));
        btnResult.setMinimumSize(new java.awt.Dimension(25, 25));
        btnResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResultMouseClicked(evt);
            }
        });

        btnClean.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnClean.setText("C");
        btnClean.setInheritsPopupMenu(true);
        btnClean.setMaximumSize(new java.awt.Dimension(25, 25));
        btnClean.setMinimumSize(new java.awt.Dimension(25, 25));
        btnClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCleanMouseClicked(evt);
            }
        });

        btnCleanEntry.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnCleanEntry.setText("CE");
        btnCleanEntry.setInheritsPopupMenu(true);
        btnCleanEntry.setMaximumSize(new java.awt.Dimension(25, 25));
        btnCleanEntry.setMinimumSize(new java.awt.Dimension(25, 25));
        btnCleanEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCleanEntryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btbMSub, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCleanEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnContrast, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1Divide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btbMSub, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCleanEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnContrast, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn1Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkClean() {
        if (clean) {
            txtDisplay.setText("");
            clean = false;
        }
        if (equalButtonIsClicked) {
            result = 0.0;
        }
        if (expressionIsClicked) {
            expressionIsClicked = false;
        }
        setExpressionButtonColor();
    }
    
    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "1");
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "2");
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "3");
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "4");
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "5");
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "6");
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "7");
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "8");
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "9");
    }//GEN-LAST:event_btn9MouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        checkClean();
        txtDisplay.setText(txtDisplay.getText() + "0");
    }//GEN-LAST:event_btn0MouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        if (!expressionIsClicked) {
            calculatePre();
            displayResult();
        }
        
        currentOperation = '+';
        expressionIsClicked = true;
        setExpressionButtonColor();
        btnAdd.setBackground(Color.yellow);
        equalButtonIsClicked = false;
        clean = true;
    }//GEN-LAST:event_btnAddMouseClicked
    
    private void btnDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseClicked
        checkClean();
        if (txtDisplay.getText().equals("")) {
            txtDisplay.setText("0.");
        } else {
            txtDisplay.setText(txtDisplay.getText() + ".");
        }
    }//GEN-LAST:event_btnDotMouseClicked

    private void btnResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultMouseClicked
        calculatePre();
        currentOperation = 'd';
        if (!txtDisplay.getText().equals("Error")) {
            displayResult();
        }
        clean = true;
        equalButtonIsClicked = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btnResultMouseClicked

    private void btnSubtractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubtractMouseClicked
        if (!expressionIsClicked) {
            calculatePre();
            displayResult();
        }
        
        currentOperation = '-';
        expressionIsClicked = true;
        setExpressionButtonColor();
        btnSubtract.setBackground(Color.yellow);
        equalButtonIsClicked = false;
        clean = true;
    }//GEN-LAST:event_btnSubtractMouseClicked

    private void btnMultiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplyMouseClicked
        if (!expressionIsClicked) {
            calculatePre();
            displayResult();
        }
        
        currentOperation = '*';
        expressionIsClicked = true;
        setExpressionButtonColor();
        btnMultiply.setBackground(Color.yellow);
        equalButtonIsClicked = false;
        clean = true;
    }//GEN-LAST:event_btnMultiplyMouseClicked

    private void btnDivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivideMouseClicked
        if (!expressionIsClicked) {
            calculatePre();
            displayResult();
        }
        
        currentOperation = '/';
        expressionIsClicked = true;
        setExpressionButtonColor();
        btnDivide.setBackground(Color.yellow);
        equalButtonIsClicked = false;
        clean = true;
    }//GEN-LAST:event_btnDivideMouseClicked

    private void btnContrastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContrastMouseClicked
        calculatePre();
        result *= -1;
        displayResult();
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btnContrastMouseClicked

    private void btnPercentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPercentMouseClicked
        equalButtonIsClicked = false;
        expressionIsClicked = false;
        Double tmpPercent = ConvertDisplayToNumber(txtDisplay.getText()) / 100;
        displayTempResult(tmpPercent);
        calculatePre();
        currentOperation = 'd';
        //-----------
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btnPercentMouseClicked

    private void btnSquareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSquareMouseClicked
        equalButtonIsClicked = false;
        expressionIsClicked = false;
        
        if (ConvertDisplayToNumber(txtDisplay.getText()) >= 0) {
            Double tmpSquare = Math.sqrt(ConvertDisplayToNumber(txtDisplay.getText()));
            displayTempResult(tmpSquare);
            calculatePre();
            currentOperation = 'd';
        } else {
            txtDisplay.setText("Error");
        }
        //-----------
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btnSquareMouseClicked

    private void btn1DivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1DivideMouseClicked
        equalButtonIsClicked = false;
        expressionIsClicked = false;
        
        if (ConvertDisplayToNumber(txtDisplay.getText()) != 0) {
            Double tmpPart = 1 / ConvertDisplayToNumber(txtDisplay.getText());
            displayTempResult(tmpPart);
            calculatePre();
            currentOperation = 'd';
        } else {
            txtDisplay.setText("Error");
        }
        //-----------
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btn1DivideMouseClicked

    private void btnMPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMPlusMouseClicked
        memoryResult += ConvertDisplayToNumber(txtDisplay.getText());
        //-----------
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btnMPlusMouseClicked

    private void btbMSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbMSubMouseClicked
        memoryResult -= ConvertDisplayToNumber(txtDisplay.getText());
        //-----------
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btbMSubMouseClicked

    private void btnMRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMRMouseClicked
        String resultString = memoryResult.toString();
        
        if (resultString.contains(".0")) {
            resultString = resultString.substring(0, resultString.length() - 2);
        }
        
        txtDisplay.setText(resultString);
        //-----------
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btnMRMouseClicked

    private void btnMCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMCMouseClicked
        memoryResult = 0.0;
        //-----------
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btnMCMouseClicked

    private void btnCleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanMouseClicked
        initLocalVariable();
        txtDisplay.setText("0");
        //-----------
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btnCleanMouseClicked

    private void btnCleanEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanEntryMouseClicked
        txtDisplay.setText("0");
        //-----------
        clean = true;
        setExpressionButtonColor();
    }//GEN-LAST:event_btnCleanEntryMouseClicked

    /**
     * Convert the number which is displayed on the screen to Double
     */
    private double ConvertDisplayToNumber(String displayString) {
        return Double.parseDouble(displayString);
    }
    
    private void calculatePre() {
        if (!equalButtonIsClicked && !expressionIsClicked) {
            recentValue = ConvertDisplayToNumber(txtDisplay.getText());
        }
        
        if (equalButtonIsClicked) {
            result = recentValue = ConvertDisplayToNumber(txtDisplay.getText());
            equalButtonIsClicked = false;
        }
        
        switch (currentOperation) {
            case '+': {
                result += recentValue;
                break;
            }
            case '-': {
                result -= recentValue;
                break;
            }
            case '*': {
                result *= recentValue;
                break;
            }
            case '/': {
                if (recentValue != 0.0) {
                    result /= recentValue;
                } else {
                    txtDisplay.setText("Error");
                }
                break;
            }
            case '#': {
                result = ConvertDisplayToNumber(txtDisplay.getText());
                break;
            }
            case 'd': break;
        }
    }
        
    
    private void displayResult() {
        String resultString = result.toString();
        if (resultString.contains(".0")) {
            resultString = resultString.substring(0, resultString.length() - 2);
        }
        txtDisplay.setText(resultString);
    }
    
    private void displayTempResult(Double tmpResult) {
        String resultString = tmpResult.toString();
        if (resultString.contains(".0")) {
            resultString = resultString.substring(0, resultString.length() - 2);
        }
        txtDisplay.setText(resultString);
    }
    
    /**
     * Change button color to default (color of Result button) 
     */
    private void setExpressionButtonColor() {
        btnAdd.setBackground(btnResult.getBackground());
        btnSubtract.setBackground(btnResult.getBackground());
        btnMultiply.setBackground(btnResult.getBackground());
        btnDivide.setBackground(btnResult.getBackground());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbMSub;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn1Divide;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnCleanEntry;
    private javax.swing.JButton btnContrast;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnMPlus;
    private javax.swing.JButton btnMR;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
